#!/usr/bin/env python3
"""Verify Phase1 action prediction accuracy.

This script compares model predictions with ground-truth actions generated by
`build_ebnav_sft.py` (or equivalent files that contain `gt_action_name` /
`gt_action_token`).
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any, Iterable


LATENT_ACTION_PATTERN = re.compile(r"<\|action_start\|>\s*(.*?)\s*(?:<\|action_end\|>|$)", re.DOTALL)
XML_ACTION_PATTERN = re.compile(r"<action>\s*(.*?)\s*</action>", re.DOTALL)

ACTION_TOKEN_TO_NAME: dict[str, str] = {
    "<|act_moveahead|>": "move_forward",
    "<|act_moveback|>": "move_backward",
    "<|act_moveright|>": "move_right",
    "<|act_moveleft|>": "move_left",
    "<|act_rotateright|>": "turn_right",
    "<|act_rotateleft|>": "turn_left",
    "<|act_lookup|>": "look_up",
    "<|act_lookdown|>": "look_down",
}

ACTION_NAME_ALIASES: dict[str, str] = {
    "moveahead": "move_forward",
    "moveback": "move_backward",
    "moveright": "move_right",
    "moveleft": "move_left",
    "rotateright": "turn_right",
    "rotateleft": "turn_left",
    "lookup": "look_up",
    "lookdown": "look_down",
}

ACTION_NAME_TO_TOKEN: dict[str, str] = {name: token for token, name in ACTION_TOKEN_TO_NAME.items()}
ACTION_NAME_TO_TOKEN.update(
    {alias: ACTION_NAME_TO_TOKEN[canonical] for alias, canonical in ACTION_NAME_ALIASES.items()}
)

PREDICTION_FIELD_CANDIDATES = (
    "prediction",
    "pred",
    "predict",
    "output",
    "response",
    "generated_text",
    "assistant_response",
    "assistant_output",
    "model_output",
    "text",
)

GT_NAME_FIELD_CANDIDATES = ("gt_action_name", "label", "target", "gold_action_name")
GT_TOKEN_FIELD_CANDIDATES = ("gt_action_token", "label_token", "gold_action_token")


def normalize_action_name(name: str) -> str:
    canonical_name = str(name).lower().strip()
    return ACTION_NAME_ALIASES.get(canonical_name, canonical_name)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate Phase1 output accuracy")
    parser.add_argument("--pred-file", type=str, required=True, help="Prediction file path: json/jsonl/parquet/csv")
    parser.add_argument(
        "--gt-file",
        type=str,
        default=None,
        help="Ground truth file path. Optional if pred-file already contains gt columns.",
    )
    parser.add_argument(
        "--pred-field",
        type=str,
        default=None,
        help="Column name for prediction text. If omitted, auto-detect.",
    )
    parser.add_argument(
        "--id-field",
        type=str,
        default=None,
        help="Join key between pred-file and gt-file. Optional; defaults to row-order join.",
    )
    parser.add_argument(
        "--save-errors",
        type=str,
        default=None,
        help="Optional output path for incorrect samples (jsonl).",
    )
    return parser.parse_args()


def _load_table(path: str) -> list[dict[str, Any]]:
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    suffix = file_path.suffix.lower()
    if suffix == ".csv":
        with open(file_path, encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))
    if suffix == ".json":
        with open(file_path, encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return [dict(item) for item in data]
        if isinstance(data, dict):
            return [dict(data)]
        raise ValueError(f"Unsupported JSON content in {path}")
    if suffix == ".jsonl":
        rows: list[dict[str, Any]] = []
        with open(file_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(dict(json.loads(line)))
        return rows
    if suffix == ".parquet":
        try:
            import pyarrow.parquet as pq
        except ImportError as exc:
            raise ImportError("Reading parquet requires `pyarrow`. Please install it or convert to json/jsonl/csv.") from exc
        table = pq.read_table(file_path)
        return table.to_pylist()
    raise ValueError(f"Unsupported file type: {path} (expect json/jsonl/parquet/csv)")


def _find_first_existing_column(rows: list[dict[str, Any]], candidates: tuple[str, ...]) -> str | None:
    if not rows:
        return None
    keys = set(rows[0].keys())
    for col in candidates:
        if col in keys:
            return col
    return None


def _extract_action_token_from_text(pred_text: Any) -> str | None:
    if pred_text is None:
        return None
    text = str(pred_text)
    if not text.strip():
        return None

    latent_match = LATENT_ACTION_PATTERN.search(text)
    if latent_match:
        region = latent_match.group(1)
        for tok in ACTION_TOKEN_TO_NAME:
            if tok in region:
                return tok

    xml_match = XML_ACTION_PATTERN.search(text)
    if xml_match:
        action_raw = xml_match.group(1).strip().split("|")[0].strip()
        action_name = normalize_action_name(action_raw)
        return ACTION_NAME_TO_TOKEN.get(action_name)

    for tok in ACTION_TOKEN_TO_NAME:
        if tok in text:
            return tok

    action_raw = text.strip().split("|")[0].strip()
    action_name = normalize_action_name(action_raw)
    if action_name in ACTION_NAME_TO_TOKEN:
        return ACTION_NAME_TO_TOKEN[action_name]
    return None


def _ensure_gt_columns(rows: list[dict[str, Any]]) -> tuple[str, str]:
    gt_name_col = _find_first_existing_column(rows, GT_NAME_FIELD_CANDIDATES)
    gt_token_col = _find_first_existing_column(rows, GT_TOKEN_FIELD_CANDIDATES)

    if gt_name_col is None and gt_token_col is None:
        raise ValueError(
            "No GT columns found. Need one of "
            f"{GT_NAME_FIELD_CANDIDATES + GT_TOKEN_FIELD_CANDIDATES}."
        )

    if gt_token_col is None:
        for row in rows:
            row["gt_action_token"] = ACTION_NAME_TO_TOKEN.get(normalize_action_name(str(row.get(gt_name_col))))
        gt_token_col = "gt_action_token"
    if gt_name_col is None:
        for row in rows:
            row["gt_action_name"] = ACTION_TOKEN_TO_NAME.get(row.get(gt_token_col))
        gt_name_col = "gt_action_name"
    return gt_name_col, gt_token_col


def _row_order_join(
    left_rows: list[dict[str, Any]],
    right_rows: list[dict[str, Any]],
    right_suffix: str = "_gt",
) -> list[dict[str, Any]]:
    n = min(len(left_rows), len(right_rows))
    if n == 0:
        raise ValueError("Empty prediction or ground-truth file.")
    joined: list[dict[str, Any]] = []
    for i in range(n):
        row = dict(left_rows[i])
        for k, v in right_rows[i].items():
            if k in row:
                row[f"{k}{right_suffix}"] = v
            else:
                row[k] = v
        joined.append(row)
    return joined


def _build_index(rows: list[dict[str, Any]], key: str) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for row in rows:
        if key in row and row[key] is not None:
            index[str(row[key])] = row
    return index


def _inner_join_on_key(
    left_rows: list[dict[str, Any]],
    right_rows: list[dict[str, Any]],
    key: str,
    right_suffix: str = "_gt",
) -> list[dict[str, Any]]:
    right_index = _build_index(right_rows, key)
    joined: list[dict[str, Any]] = []
    for left in left_rows:
        if key not in left or left[key] is None:
            continue
        right = right_index.get(str(left[key]))
        if right is None:
            continue
        row = dict(left)
        for k, v in right.items():
            if k in row and k != key:
                row[f"{k}{right_suffix}"] = v
            elif k != key:
                row[k] = v
        joined.append(row)
    return joined


def _prepare_joined_table(args: argparse.Namespace) -> tuple[list[dict[str, Any]], str]:
    pred_rows = _load_table(args.pred_file)

    pred_col = args.pred_field or _find_first_existing_column(pred_rows, PREDICTION_FIELD_CANDIDATES)
    if pred_col is None:
        raise ValueError(
            "Cannot find prediction column automatically. "
            f"Try --pred-field. Candidates: {PREDICTION_FIELD_CANDIDATES}"
        )
    for row in pred_rows:
        row["__pred_text__"] = row.get(pred_col)

    if args.gt_file is None:
        joined = pred_rows
    else:
        gt_rows = _load_table(args.gt_file)
        if args.id_field:
            if not pred_rows or args.id_field not in pred_rows[0]:
                raise ValueError(f"--id-field `{args.id_field}` not found in both files.")
            if not gt_rows or args.id_field not in gt_rows[0]:
                raise ValueError(f"--id-field `{args.id_field}` not found in both files.")
            joined = _inner_join_on_key(pred_rows, gt_rows, key=args.id_field)
        else:
            joined = _row_order_join(pred_rows, gt_rows)
    return joined, pred_col


def _safe_ratio(num: int, den: int) -> float:
    return float(num) / float(den) if den > 0 else 0.0


def _groupby_count(rows: Iterable[dict[str, Any]], key: str) -> dict[str, dict[str, int]]:
    stats: dict[str, dict[str, int]] = {}
    for row in rows:
        action = str(row.get(key))
        if action not in stats:
            stats[action] = {"total": 0, "correct": 0}
        stats[action]["total"] += 1
        stats[action]["correct"] += int(bool(row.get("is_correct")))
    return stats


def main() -> None:
    args = parse_args()
    joined, pred_col = _prepare_joined_table(args)
    gt_name_col, gt_token_col = _ensure_gt_columns(joined)

    for row in joined:
        row["pred_action_token"] = _extract_action_token_from_text(row.get("__pred_text__"))
        row["pred_action_name"] = ACTION_TOKEN_TO_NAME.get(row.get("pred_action_token"))
        row["is_correct"] = row.get("pred_action_token") == row.get(gt_token_col)

    total = len(joined)
    valid_rows = [row for row in joined if row.get("pred_action_token") and row.get(gt_token_col)]
    valid = len(valid_rows)
    correct = sum(1 for row in valid_rows if row.get("is_correct"))
    accuracy = _safe_ratio(correct, valid)
    parse_fail = total - valid

    print("===== Phase1 Accuracy Report =====")
    print(f"Pred file     : {args.pred_file}")
    print(f"GT file       : {args.gt_file or '(use GT in pred file)'}")
    print(f"Pred field    : {pred_col}")
    print(f"GT name field : {gt_name_col}")
    print(f"GT token field: {gt_token_col}")
    print("-" * 36)
    print(f"Total samples : {total}")
    print(f"Valid parsed  : {valid}")
    print(f"Parse failed  : {parse_fail}")
    print(f"Correct       : {correct}")
    print(f"Accuracy      : {accuracy:.4%}")

    by_action = _groupby_count(valid_rows, gt_name_col)
    if by_action:
        per_action_rows = []
        for action, stat in by_action.items():
            per_action_rows.append(
                {
                    "action": action,
                    "total": stat["total"],
                    "correct": stat["correct"],
                    "accuracy": _safe_ratio(stat["correct"], stat["total"]),
                }
            )
        per_action_rows.sort(key=lambda x: x["accuracy"])
        print("\n===== Per-Action Accuracy =====")
        for row in per_action_rows:
            print(
                f"{row['action']:<16} total={row['total']:<6} "
                f"correct={row['correct']:<6} accuracy={row['accuracy']:.2%}"
            )

    if args.save_errors:
        errors = [row for row in valid_rows if not row.get("is_correct")]
        out_path = Path(args.save_errors)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            for row in errors:
                record = {
                    "pred_text": row.get("__pred_text__"),
                    "pred_action_token": row.get("pred_action_token"),
                    "pred_action_name": row.get("pred_action_name"),
                    "gt_action_token": row.get(gt_token_col),
                    "gt_action_name": row.get(gt_name_col),
                }
                for key in ("episode_id", "step_id", "trajectory_index", "plan_action_index", "source"):
                    if key in row:
                        record[key] = row.get(key)
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        print(f"\nSaved error samples to: {out_path}")


if __name__ == "__main__":
    main()
